# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    handler: src/graphql.graphqlHandler
    events:
    - http:
        method: post
        cors: true
    - http:
        method: get
        cors: true
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  serverless-offline:
    port: 4000